//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_m3u8DL_CLI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N_m3u8DL_CLI.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 二进制合并...请耐心等待 的本地化字符串。
        /// </summary>
        public static string binaryMergingPleaseWait {
            get {
                return ResourceManager.GetString("binaryMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在判断尾分片是否有效... 的本地化字符串。
        /// </summary>
        public static string checkingLast {
            get {
                return ResourceManager.GetString("checkingLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭完整性检查 的本地化字符串。
        /// </summary>
        public static string disableIntegrityCheck {
            get {
                return ResourceManager.GetString("disableIntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杜比视界内容，使用二进制合并...请耐心等待 的本地化字符串。
        /// </summary>
        public static string dolbyVisionContentMerging {
            get {
                return ResourceManager.GetString("dolbyVisionContentMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载完毕 的本地化字符串。
        /// </summary>
        public static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成数量  的本地化字符串。
        /// </summary>
        public static string downloadedCount {
            get {
                return ResourceManager.GetString("downloadedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败, 程序退出 的本地化字符串。
        /// </summary>
        public static string downloadFailed {
            get {
                return ResourceManager.GetString("downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载外挂音频... 的本地化字符串。
        /// </summary>
        public static string downloadingExternalAudioTrack {
            get {
                return ResourceManager.GetString("downloadingExternalAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载外挂字幕... 的本地化字符串。
        /// </summary>
        public static string downloadingExternalSubtitleTrack {
            get {
                return ResourceManager.GetString("downloadingExternalSubtitleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载首分片... 的本地化字符串。
        /// </summary>
        public static string downloadingFirstSegement {
            get {
                return ResourceManager.GetString("downloadingFirstSegement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取m3u8内容 的本地化字符串。
        /// </summary>
        public static string downloadingM3u8 {
            get {
                return ResourceManager.GetString("downloadingM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取m3u8 key... 的本地化字符串。
        /// </summary>
        public static string downloadingM3u8Key {
            get {
                return ResourceManager.GetString("downloadingM3u8Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载MAP文件... 的本地化字符串。
        /// </summary>
        public static string downloadingMapFile {
            get {
                return ResourceManager.GetString("downloadingMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制退出: Ctrl+C 的本地化字符串。
        /// </summary>
        public static string ExitedCtrlC {
            get {
                return ResourceManager.GetString("ExitedCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制退出: 强制 的本地化字符串。
        /// </summary>
        public static string ExitedForce {
            get {
                return ResourceManager.GetString("ExitedForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果输出至 [ffreport.log] 的本地化字符串。
        /// </summary>
        public static string ffmpegDone {
            get {
                return ResourceManager.GetString("ffmpegDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在PATH和程序路径下找不到 ffmpeg 的本地化字符串。
        /// </summary>
        public static string ffmpegLost {
            get {
                return ResourceManager.GetString("ffmpegLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用ffmpeg合并...请耐心等待 的本地化字符串。
        /// </summary>
        public static string ffmpegMergingPleaseWait {
            get {
                return ResourceManager.GetString("ffmpegMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请下载ffmpeg.exe并把他放到程序同目录. 的本地化字符串。
        /// </summary>
        public static string ffmpegTip {
            get {
                return ResourceManager.GetString("ffmpegTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件时长： 的本地化字符串。
        /// </summary>
        public static string fileDuration {
            get {
                return ResourceManager.GetString("fileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称： 的本地化字符串。
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别到外挂音频轨道 的本地化字符串。
        /// </summary>
        public static string hasExternalAudioTrack {
            get {
                return ResourceManager.GetString("hasExternalAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别到外挂字幕轨道 的本地化字符串。
        /// </summary>
        public static string hasExternalSubtitleTrack {
            get {
                return ResourceManager.GetString("hasExternalSubtitleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定Baseurl 的本地化字符串。
        /// </summary>
        public static string Help_baseUrl {
            get {
                return ResourceManager.GetString("Help_baseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭混流中的日期写入 的本地化字符串。
        /// </summary>
        public static string Help_disableDateInfo {
            get {
                return ResourceManager.GetString("Help_disableDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不检测分片数量是否完整 的本地化字符串。
        /// </summary>
        public static string Help_disableIntegrityCheck {
            get {
                return ResourceManager.GetString("Help_disableIntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅下载视频的一部分分片或长度 的本地化字符串。
        /// </summary>
        public static string Help_downloadRange {
            get {
                return ResourceManager.GetString("Help_downloadRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并时仅封装音频轨道 的本地化字符串。
        /// </summary>
        public static string Help_enableAudioOnly {
            get {
                return ResourceManager.GetString("Help_enableAudioOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启二进制合并分片 的本地化字符串。
        /// </summary>
        public static string Help_enableBinaryMerge {
            get {
                return ResourceManager.GetString("Help_enableBinaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启下载后删除临时文件夹的功能 的本地化字符串。
        /// </summary>
        public static string Help_enableDelAfterDone {
            get {
                return ResourceManager.GetString("Help_enableDelAfterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启混流mp4的FastStart特性 的本地化字符串。
        /// </summary>
        public static string Help_enableMuxFastStart {
            get {
                return ResourceManager.GetString("Help_enableMuxFastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启仅解析模式(程序只进行到meta.json) 的本地化字符串。
        /// </summary>
        public static string Help_enableParseOnly {
            get {
                return ResourceManager.GetString("Help_enableParseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定请求头，格式 key:value 使用|分割不同的key&amp;value 的本地化字符串。
        /// </summary>
        public static string Help_headers {
            get {
                return ResourceManager.GetString("Help_headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接或文件 的本地化字符串。
        /// </summary>
        public static string Help_input {
            get {
                return ResourceManager.GetString("Help_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直播录制时，达到此长度自动退出软件(HH:MM:SS) 的本地化字符串。
        /// </summary>
        public static string Help_liveRecDur {
            get {
                return ResourceManager.GetString("Help_liveRecDur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置下载速度上限(单位为KB/s) 的本地化字符串。
        /// </summary>
        public static string Help_maxSpeed {
            get {
                return ResourceManager.GetString("Help_maxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定程序的最大线程数 的本地化字符串。
        /// </summary>
        public static string Help_maxThreads {
            get {
                return ResourceManager.GetString("Help_maxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定程序的最小线程数 的本地化字符串。
        /// </summary>
        public static string Help_minThreads {
            get {
                return ResourceManager.GetString("Help_minThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用外部json文件定义混流选项 的本地化字符串。
        /// </summary>
        public static string Help_muxSetJson {
            get {
                return ResourceManager.GetString("Help_muxSetJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用自动合并 的本地化字符串。
        /// </summary>
        public static string Help_noMerge {
            get {
                return ResourceManager.GetString("Help_noMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不自动使用系统代理 的本地化字符串。
        /// </summary>
        public static string Help_noProxy {
            get {
                return ResourceManager.GetString("Help_noProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置HTTP/SOCKS5代理, 如 http://127.0.0.1:8080 的本地化字符串。
        /// </summary>
        public static string Help_proxyAddress {
            get {
                return ResourceManager.GetString("Help_proxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册m3u8dl链接协议 的本地化字符串。
        /// </summary>
        public static string Help_registerUrlProtocol {
            get {
                return ResourceManager.GetString("Help_registerUrlProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定程序的重试次数 的本地化字符串。
        /// </summary>
        public static string Help_retryCount {
            get {
                return ResourceManager.GetString("Help_retryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定存储文件名(不包括后缀) 的本地化字符串。
        /// </summary>
        public static string Help_saveName {
            get {
                return ResourceManager.GetString("Help_saveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当速度低于此值时，重试(单位为KB/s) 的本地化字符串。
        /// </summary>
        public static string Help_stopSpeed {
            get {
                return ResourceManager.GetString("Help_stopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定程序网络请求的超时时间(单位为秒) 的本地化字符串。
        /// </summary>
        public static string Help_timeOut {
            get {
                return ResourceManager.GetString("Help_timeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消注册m3u8dl链接协议 的本地化字符串。
        /// </summary>
        public static string Help_unregisterUrlProtocol {
            get {
                return ResourceManager.GetString("Help_unregisterUrlProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用Base64字符串定义AES-128解密KEY 的本地化字符串。
        /// </summary>
        public static string Help_useKeyBase64 {
            get {
                return ResourceManager.GetString("Help_useKeyBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用外部16字节文件定义AES-128解密KEY 的本地化字符串。
        /// </summary>
        public static string Help_useKeyFile {
            get {
                return ResourceManager.GetString("Help_useKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用HEX字符串定义AES-128解密IV 的本地化字符串。
        /// </summary>
        public static string Help_useKeyIV {
            get {
                return ResourceManager.GetString("Help_useKeyIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定程序工作目录 的本地化字符串。
        /// </summary>
        public static string Help_workDir {
            get {
                return ResourceManager.GetString("Help_workDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的m3u8 的本地化字符串。
        /// </summary>
        public static string invalidM3u8 {
            get {
                return ResourceManager.GetString("invalidM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址无效 的本地化字符串。
        /// </summary>
        public static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别为直播流, 开始录制... 的本地化字符串。
        /// </summary>
        public static string liveStreamFoundAndRecoding {
            get {
                return ResourceManager.GetString("liveStreamFoundAndRecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别到大师列表 的本地化字符串。
        /// </summary>
        public static string masterListFound {
            get {
                return ResourceManager.GetString("masterListFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到更新，版本：{0}! 新版下载成功，请您自行替换 的本地化字符串。
        /// </summary>
        public static string newerVerisonDownloaded {
            get {
                return ResourceManager.GetString("newerVerisonDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到更新，版本：{0}! 新版下载失败，请您自行下载 的本地化字符串。
        /// </summary>
        public static string newerVerisonDownloadFailed {
            get {
                return ResourceManager.GetString("newerVerisonDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到更新，版本：{0}! 正在尝试自动下载新版 的本地化字符串。
        /// </summary>
        public static string newerVisionDetected {
            get {
                return ResourceManager.GetString("newerVisionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持{0}加密方式,将不被处理,且强制开启二进制合并 的本地化字符串。
        /// </summary>
        public static string notSupportMethod {
            get {
                return ResourceManager.GetString("notSupportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析m3u8成功, 程序退出 的本地化字符串。
        /// </summary>
        public static string parseExit {
            get {
                return ResourceManager.GetString("parseExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析m3u8内容 的本地化字符串。
        /// </summary>
        public static string parsingM3u8 {
            get {
                return ResourceManager.GetString("parsingM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分片大于1800个，执行分部合并中... 的本地化字符串。
        /// </summary>
        public static string partialMergingPleaseWait {
            get {
                return ResourceManager.GetString("partialMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键退出. 的本地化字符串。
        /// </summary>
        public static string pressAnyKeyExit {
            get {
                return ResourceManager.GetString("pressAnyKeyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取文件信息... 的本地化字符串。
        /// </summary>
        public static string readingFileInfo {
            get {
                return ResourceManager.GetString("readingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制已到达限定长度 的本地化字符串。
        /// </summary>
        public static string recordLimitReached {
            get {
                return ResourceManager.GetString("recordLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册m3u8dl链接协议失败！ 的本地化字符串。
        /// </summary>
        public static string registerUrlProtocolFailed {
            get {
                return ResourceManager.GetString("registerUrlProtocolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册m3u8dl链接协议成功！ 的本地化字符串。
        /// </summary>
        public static string registerUrlProtocolSuccessful {
            get {
                return ResourceManager.GetString("registerUrlProtocolSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将文件转换到 MPEG-TS 封装： 的本地化字符串。
        /// </summary>
        public static string remuxToMPEGTS {
            get {
                return ResourceManager.GetString("remuxToMPEGTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试次数  的本地化字符串。
        /// </summary>
        public static string retryCount {
            get {
                return ResourceManager.GetString("retryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径： 的本地化字符串。
        /// </summary>
        public static string savePath {
            get {
                return ResourceManager.GetString("savePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总分片： 的本地化字符串。
        /// </summary>
        public static string segCount {
            get {
                return ResourceManager.GetString("segCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择分片： 的本地化字符串。
        /// </summary>
        public static string selectedCount {
            get {
                return ResourceManager.GetString("selectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已自动选择最高清晰度 的本地化字符串。
        /// </summary>
        public static string selectPlaylist {
            get {
                return ResourceManager.GetString("selectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到了某些错误! 的本地化字符串。
        /// </summary>
        public static string SomethingWasWrong {
            get {
                return ResourceManager.GetString("SomethingWasWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载文件 的本地化字符串。
        /// </summary>
        public static string startDownloading {
            get {
                return ResourceManager.GetString("startDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始合并分片... 的本地化字符串。
        /// </summary>
        public static string startMerging {
            get {
                return ResourceManager.GetString("startMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始解析  的本地化字符串。
        /// </summary>
        public static string startParsing {
            get {
                return ResourceManager.GetString("startParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始解析MPD内容... 的本地化字符串。
        /// </summary>
        public static string startParsingMpd {
            get {
                return ResourceManager.GetString("startParsingMpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新解析m3u8... 的本地化字符串。
        /// </summary>
        public static string startReParsing {
            get {
                return ResourceManager.GetString("startReParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务结束 的本地化字符串。
        /// </summary>
        public static string taskDone {
            get {
                return ResourceManager.GetString("taskDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消注册m3u8dl链接协议失败！ 的本地化字符串。
        /// </summary>
        public static string unregisterUrlProtocolFailed {
            get {
                return ResourceManager.GetString("unregisterUrlProtocolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消注册m3u8dl链接协议成功！ 的本地化字符串。
        /// </summary>
        public static string unregisterUrlProtocolSuccessful {
            get {
                return ResourceManager.GetString("unregisterUrlProtocolSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待下载完成... 的本地化字符串。
        /// </summary>
        public static string waitForCompletion {
            get {
                return ResourceManager.GetString("waitForCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写出playLists.json 的本地化字符串。
        /// </summary>
        public static string wrtingMasterMeta {
            get {
                return ResourceManager.GetString("wrtingMasterMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写出meta.json 的本地化字符串。
        /// </summary>
        public static string wrtingMeta {
            get {
                return ResourceManager.GetString("wrtingMeta", resourceCulture);
            }
        }
    }
}
